# Generated by Django 4.0.1 on 2022-01-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('size', models.SmallIntegerField(verbose_name='Размер')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(default='Описания нет', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='room_photos', verbose_name='Картинка')),
                ('schedule', models.JSONField(default=dict, verbose_name='Расписание')),
                ('category', models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('booking_begin', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomApp.room', verbose_name='Помещение')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('booking_begin', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomApp.room', verbose_name='Помещение')),
                ('temp_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Временный владелец')),
            ],
        ),
    ]
