# Generated by Django 4.1.3 on 2023-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0003_alter_roomquery_sch_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos', verbose_name='Картинка'),
        ),
    ]
