# Generated by Django 4.1.3 on 2023-01-25 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0006_alter_roomquery_sch_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Договор'),
        ),
    ]
