# Generated by Django 4.0.2 on 2022-02-04 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipApp', '0005_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipbooking',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Договор'),
        ),
    ]
