# Generated by Django 4.0.2 on 2022-02-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipApp', '0008_alter_equipquery_sch_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='/static/main/img/default_image.jpg', upload_to='equip_photos', verbose_name='Картинка'),
        ),
    ]
