# Generated by Django 4.1.3 on 2023-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipApp', '0010_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расписание'),
        ),
    ]
