# Generated by Django 4.1.3 on 2023-01-24 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EquipApp', '0013_alter_equipquery_sch_rep'),
        ('RoomApp', '0006_alter_roomquery_sch_rep'),
        ('main', '0010_delete_schrep_schoolrepresentative_school_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolRepresentative',
            new_name='SchRep',
        ),
    ]
