# Generated by Django 4.1.3 on 2023-02-02 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_rename_schoolrepresentative_schrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schrep',
            name='credential_id',
        ),
        migrations.CreateModel(
            name='SupplyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Индификатор сертификата')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('supply_manager', 'Can be a Supply Manager')],
            },
        ),
    ]
