# Generated by Django 4.0.1 on 2022-01-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('description', models.TextField(default='Описания нет', max_length=1000, verbose_name='Описание')),
                ('address', models.CharField(default='нет', max_length=50, verbose_name='Адрес проведения')),
                ('max_places', models.SmallIntegerField(verbose_name='Максимальное количество мест')),
                ('duration', models.DurationField(verbose_name='Длительность лекции')),
                ('form', models.CharField(max_length=20, verbose_name='Форма проведения')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='lecture_photos', verbose_name='Картинка')),
                ('category', models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Организатор')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='LectureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureApp.lecture', verbose_name='Лекция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='target_audience',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='LectureApp.targetaudience', verbose_name='Целевая аудитория'),
        ),
    ]
