# Generated by Django 4.1.3 on 2023-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectureApp', '0002_alter_lecture_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lecture_photos', verbose_name='Картинка'),
        ),
    ]
