# Generated by Django 4.0.2 on 2022-02-04 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school_sign_schrep_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='school_signs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pfx'])]),
        ),
        migrations.AlterField(
            model_name='schrep',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='sch_rep_signs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pfx'])]),
        ),
    ]
