# Generated by Django 4.1.3 on 2023-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_sign_password_schrep_sign_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
