# Generated by Django 4.1.3 on 2023-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_school_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schrep',
            options={'permissions': [('school_rep', 'Can be a SchRep')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('teacher', 'Can be a teacher')]},
        ),
    ]
