# Generated by Django 4.1.3 on 2023-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_schrep_options_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Индификатор сертификата')),
            ],
            options={
                'permissions': [('school_rep', 'Can be a SchRep')],
            },
        ),
        migrations.RemoveField(
            model_name='schrep',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schrep',
            name='user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sign_image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sign_password',
        ),
        migrations.AddField(
            model_name='school',
            name='credential_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Индификатор сертификата'),
        ),
    ]
