# Generated by Django 4.0.1 on 2022-01-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LectureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='target_audience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='LectureApp.targetaudience', verbose_name='Целевая аудитория'),
        ),
    ]
