# Generated by Django 4.0.1 on 2022-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaudience',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
    ]
