# Generated by Django 4.0.1 on 2022-01-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LectureApp', '0002_alter_targetaudience_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='target_audience',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='LectureApp.targetaudience', verbose_name='Целевая аудитория'),
        ),
    ]
