# Generated by Django 4.0.2 on 2022-02-05 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_sign_password_schrep_sign_password'),
        ('RoomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='roomquery',
            name='sch_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schrep', verbose_name='Представитель'),
        ),
    ]
