# Generated by Django 4.1.3 on 2023-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расписание'),
        ),
    ]
