# Generated by Django 4.0.1 on 2022-01-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('EquipApp', '0002_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория'),
        ),
    ]
