# Generated by Django 4.0.2 on 2022-02-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_sign_password_schrep_sign_password'),
        ('EquipApp', '0007_equipquery_sch_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipquery',
            name='sch_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schrep', verbose_name='Представитель'),
        ),
    ]
