# Generated by Django 4.1.3 on 2023-01-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_schoolrepresentative_remove_schrep_school_and_more'),
        ('EquipApp', '0012_alter_equipbooking_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipquery',
            name='sch_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolrepresentative', verbose_name='Представитель'),
        ),
    ]
