# Generated by Django 4.0.2 on 2022-02-04 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_school_sign_image_schrep_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(default='Описания нет', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='school_photos', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='school_signs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pfx'])], verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_sign_images', verbose_name='Картинка подписи'),
        ),
        migrations.AlterField(
            model_name='schrep',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='sch_rep_signs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pfx'])], verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='schrep',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='sch_rep_sign_images', verbose_name='Картинка подписи'),
        ),
    ]
