# Generated by Django 4.0.1 on 2022-01-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('description', models.TextField(default='Описания нет', max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='equip_photos', verbose_name='Картинка')),
                ('schedule', models.JSONField(verbose_name='Расписание')),
                ('category', models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='EquipQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('booking_begin', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipApp.equipment', verbose_name='Оборудование')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='EquipBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('booking_begin', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EquipApp.equipment', verbose_name='Оборудование')),
                ('temp_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Временный владелец')),
            ],
        ),
    ]
