# Generated by Django 4.0.1 on 2022-01-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='schedule',
            field=models.JSONField(default=dict, verbose_name='Расписание'),
        ),
    ]
