# Generated by Django 4.0.1 on 2022-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('EquipApp', '0003_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(8), to='main.category', verbose_name='Категория'),
        ),
    ]
